# Generated by Django 4.2.30 on 2026-05-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.PositiveIntegerField(verbose_name='Data Year')),
                ('operator_name', models.CharField(max_length=200, verbose_name="Operator's Name")),
                ('trading_name', models.CharField(blank=True, max_length=200, verbose_name='Trading Name')),
                ('county', models.CharField(choices=[('Antrim', 'Antrim'), ('Armagh', 'Armagh'), ('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Derry', 'Derry'), ('Donegal', 'Donegal'), ('Down', 'Down'), ('Dublin', 'Dublin'), ('Fermanagh', 'Fermanagh'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Tyrone', 'Tyrone'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], max_length=50, verbose_name='County of Establishment')),
                ('annual_revenue', models.DecimalField(decimal_places=2, help_text='Include online/pre-paid tickets, Young Adult and Student Card revenue. Exclude Free Travel Scheme, NTA Grant, contractual, and private hire revenues.', max_digits=14, verbose_name='Annual Total Ticket Revenue (€)')),
                ('taxsaver', models.BooleanField(verbose_name='TaxSaver Participant?')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operator Return',
                'verbose_name_plural': 'Operator Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.CharField(max_length=50, verbose_name='RES ID')),
                ('vehicle_reg', models.CharField(max_length=20, verbose_name='Vehicle Reg No.')),
                ('regularly_deployed', models.BooleanField(verbose_name='Regularly deployed on scheduled services?')),
                ('make', models.CharField(max_length=100, verbose_name='Make')),
                ('model_version', models.CharField(max_length=100, verbose_name='Model / Version')),
                ('transmission', models.CharField(max_length=50, verbose_name='Transmission')),
                ('engine_type', models.CharField(max_length=50, verbose_name='Engine Type')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20, verbose_name='Fuel Type')),
                ('euro_standard', models.CharField(blank=True, choices=[('', 'Not known'), ('Euro I', 'Euro I'), ('Euro II', 'Euro II'), ('Euro III', 'Euro III'), ('Euro IV', 'Euro IV'), ('Euro V', 'Euro V'), ('Euro VI', 'Euro VI'), ('Euro VII', 'Euro VII')], max_length=20, verbose_name='Euro Emission Standard')),
                ('make_model_correct', models.BooleanField(verbose_name='Are the make/model/engine type details correct?')),
                ('seats_on_record', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seats on record')),
                ('correct_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Correct number of seats (if different)')),
                ('avl_gps', models.BooleanField(verbose_name='Vehicle has AVL/GPS on board?')),
                ('operator_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='returns.operatorreturn')),
            ],
            options={
                'verbose_name': 'Vehicle Emission Record',
            },
        ),
        migrations.CreateModel(
            name='VehicleAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.CharField(max_length=50, verbose_name='RES ID')),
                ('vehicle_reg', models.CharField(max_length=20, verbose_name='Vehicle Reg No.')),
                ('wheelchair_spaces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of wheelchair spaces')),
                ('wheelchair_access_type', models.CharField(blank=True, choices=[('Low-floor', 'Low-floor vehicle suitable for wheelchair access'), ('Lift', 'Vehicle with lift suitable for wheelchair access'), ('Both', 'Both low-floor and has a wheelchair lift'), ('None', 'Not wheelchair accessible')], max_length=50, verbose_name='Wheelchair access type')),
                ('mechanical_ramp', models.BooleanField(default=False, verbose_name='Mechanical access ramp?')),
                ('centre_door_ramps', models.BooleanField(default=False, verbose_name='Equipped with centre door ramps?')),
                ('exterior_displays', models.BooleanField(default=False, verbose_name='Exterior backlit route displays?')),
                ('interior_stop_displays', models.BooleanField(default=False, verbose_name='Interior stop displays?')),
                ('audio_announcements', models.BooleanField(default=False, verbose_name='Interior automated audible stop announcements?')),
                ('yellow_handrails', models.BooleanField(default=False, verbose_name='Yellow coloured handrails?')),
                ('priority_seating', models.BooleanField(default=False, verbose_name='Priority seating?')),
                ('contrasting_seat_covers', models.BooleanField(default=False, verbose_name='Seat covers contrasting with floor colour?')),
                ('induction_loop', models.BooleanField(default=False, verbose_name='Induction loop system?')),
                ('operator_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='returns.operatorreturn')),
            ],
            options={
                'verbose_name': 'Vehicle Accessibility Record',
            },
        ),
        migrations.CreateModel(
            name='LicenceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_no', models.CharField(blank=True, max_length=50, verbose_name='Licence No')),
                ('route_no', models.CharField(max_length=50, verbose_name='Route No')),
                ('on_free_travel', models.BooleanField(verbose_name='On Free Travel Scheme?')),
                ('on_yasc', models.BooleanField(verbose_name='On Young Adult / Student Card (YASC)?')),
                ('date_joined', models.DateField(verbose_name='Date Joined Scheme')),
                ('service_commenced', models.BooleanField(verbose_name='Has the service commenced?')),
                ('service_ceased', models.BooleanField(verbose_name='Has the service ceased?')),
                ('date_ceased', models.DateField(blank=True, null=True, verbose_name='Date Ceased (if applicable)')),
                ('total_passenger_journeys', models.PositiveIntegerField(verbose_name='Total Annual Passenger Journeys')),
                ('free_travel_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Free Travel Passengers as % of all journeys')),
                ('km_operated', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='2024 Kilometres Operated')),
                ('daily_pvr', models.PositiveIntegerField(verbose_name='2024 Daily PVR')),
                ('operator_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='returns.operatorreturn')),
            ],
            options={
                'verbose_name': 'Licence Return',
                'ordering': ['route_no'],
            },
        ),
    ]
