# Generated by Django 4.2.30 on 2026-05-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('operator_name', models.CharField(max_length=200)),
                ('operator_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to revoke access.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('operator_return', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access', to='returns.operatorreturn')),
            ],
            options={
                'verbose_name': 'Operator Access',
                'verbose_name_plural': 'Operator Accesses',
            },
        ),
    ]
