# Generated by Django 4.2.30 on 2026-05-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_operatoraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by', models.CharField(blank=True, help_text='Leave blank if completing digitally.', max_length=200, verbose_name='Signed')),
                ('printed_name', models.CharField(blank=True, help_text='Leave blank if completing digitally.', max_length=200, verbose_name='Print name in block capitals')),
                ('declaration_date', models.DateField(verbose_name='Date')),
                ('position_in_company', models.CharField(max_length=200, verbose_name='Position in Company (block capitals)')),
                ('operator_return', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='returns.operatorreturn')),
            ],
            options={
                'verbose_name': 'Declaration',
            },
        ),
    ]
