# Generated by Django 4.2.30 on 2026-05-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorreturn',
            name='taxsaver_other',
            field=models.TextField(blank=True, help_text='Required when "Other" is selected above.', verbose_name='TaxSaver — other details'),
        ),
        migrations.AlterField(
            model_name='operatorreturn',
            name='taxsaver',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('other', 'Other')], default='no', max_length=10, verbose_name='TaxSaver Tickets: Offered?'),
        ),
    ]
