# Generated by Django 4.2.30 on 2026-05-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_operatorreturn_taxsaver_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRouteUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(max_length=50)),
                ('usage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_usages', to='returns.vehicleemission')),
            ],
            options={
                'verbose_name': 'Vehicle Route Usage',
                'ordering': ['route_no'],
                'unique_together': {('vehicle', 'route_no')},
            },
        ),
    ]
