# Generated by Django 4.2.30 on 2026-05-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0005_vehicle_route_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.CharField(blank=True, max_length=50)),
                ('vehicle_reg', models.CharField(max_length=20)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('transmission', models.CharField(blank=True, max_length=50)),
                ('engine_type', models.CharField(blank=True, max_length=50)),
                ('seats_on_record', models.PositiveIntegerField(blank=True, null=True)),
                ('operator_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_vehicles', to='returns.operatoraccess')),
            ],
            options={
                'verbose_name': 'Seed Vehicle',
                'ordering': ['res_id', 'vehicle_reg'],
                'unique_together': {('operator_access', 'vehicle_reg')},
            },
        ),
        migrations.CreateModel(
            name='SeedLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(max_length=50)),
                ('operator_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_licences', to='returns.operatoraccess')),
            ],
            options={
                'verbose_name': 'Seed Licence',
                'ordering': ['route_no'],
                'unique_together': {('operator_access', 'route_no')},
            },
        ),
    ]
