# Generated by Django 4.2.30 on 2026-05-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0009_operatoraccess_is_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seedlicence',
            options={'ordering': ['year', 'route_no'], 'verbose_name': 'Seed Licence'},
        ),
        migrations.AlterModelOptions(
            name='seedvehicle',
            options={'ordering': ['year', 'res_id', 'vehicle_reg'], 'verbose_name': 'Seed Vehicle'},
        ),
    ]
